###

GET http://127.0.0.1:8001/staff/attendance/list
Content-Type: application/json

###
GET http://localhost:8002/manager/departments
Content-Type: application/json


###
GET http://localhost:8001/staff/people/by-department?department=会计部门
Content-Type: application/json
